version: "3"

services:
  app:
    container_name: sns-app
    build: ./app
    volumes:
      - ./app:/go/src/app
    depends_on: 
      - db
    ports:
      - 8000:8080
    tty: true

  db:
    container_name: sns-db
    image: postgres
    volumes:
      # - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: sns_user
      POSTGRES_PASSWORD: sns123456789
      POSTGRES_DB: sns_db
      TZ: 'Asia/Tokyo'
    ports:
      - 5432:5432
