version: "3"

services:
  app:
    container_name: sns-app
    build: ./
    volumes:
      - ./:/go/src/app
    depends_on: 
      - db
    environment:
      PORT: 8080
      DATABASE_URL: "host=db user=sns_user password=sns123456789 dbname=sns_db sslmode=disable"
    ports:
      - 8000:8080
    tty: true

  db:
    container_name: sns-db
    image: postgres
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: sns_user
      POSTGRES_PASSWORD: sns123456789
      POSTGRES_DB: sns_db
      TZ: 'Asia/Tokyo'
    ports:
      - 5432:5432
